### ISSUE TITLE
Virheitä Python versiolla 3.5.4

### ISSUE THREAD

**Issue by rollecode** [Mikrobitti/6-17-saabotti#1]
Moi!

Mielenkiintoinen projekti! mielestäni kaikki dependenssit kunnossa, mutta sain tällaista virhettä, osaisitko autella?

````
(venv) [12:43:20] rolle 6-17-saabotti $ python --version
Python 3.5.4
(venv) [12:43:26] rolle 6-17-saabotti $ python weather.py 
Traceback (most recent call last):
  File "weather.py", line 9, in <module>
    v = libvoikko.Voikko(u"fi")
  File "/home/rolle/venv/lib64/python3.5/site-packages/libvoikko.py", line 433, in __init__
    self.__lib = self.__getLib()
  File "/home/rolle/venv/lib64/python3.5/site-packages/libvoikko.py", line 419, in __getLib
    return VoikkoLibrary.open(path=cls._sharedLibrarySearchPath)
  File "/home/rolle/venv/lib64/python3.5/site-packages/libvoikko.py", line 302, in open
    return cls(fileName)
  File "/home/rolle/venv/lib64/python3.5/site-packages/libvoikko.py", line 346, in __init__
    self.voikkoInsertHyphensCstr.argtypes = [c_void_p, c_char_p, c_char_p, c_int]
  File "/usr/lib64/python3.5/ctypes/__init__.py", line 359, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib64/python3.5/ctypes/__init__.py", line 364, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib64/libvoikko.so.1: undefined symbol: voikkoInsertHyphensCstr
Exception ignored in: <bound method Voikko.__del__ of <libvoikko.Voikko object at 0x7f59607ff208>>
Traceback (most recent call last):
  File "/home/rolle/venv/lib64/python3.5/site-packages/libvoikko.py", line 443, in __del__
    self.terminate()
  File "/home/rolle/venv/lib64/python3.5/site-packages/libvoikko.py", line 473, in terminate
    if self.__handle:
AttributeError: 'Voikko' object has no attribute '_Voikko__handle'
(venv) [12:43:29] rolle 6-17-saabotti $ 
````

**Comment by roopeux** [comment]
Ronilla varmaan vastauksen tarve jo ohi, mutta sama virheilmoitus tuli itselle tilanteessa, jossa libvoikosta oli vahingossa asennettuna pari kolme kopiota roottina ja userina.  Pip3 uninstall libvoikko korjasi tilanteen.

**Comment by jamesstoneco** [comment]
This was fixed for me by installing in the os the `libvoikko` package (in addition to the python package), for example on macosx `brew install libvoikko`

**Comment by rollecode** [comment]
@roopeux @jamesstoneco Yeah, no need for this any more, but I was running it on fedora and something awry with libvoikko because could not get it to work properly... current python version for me is 3.8.3 and (Fedora 31) so I can imagine this tool will be deprecated soon.
